mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail,
         name='post_detail'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('add/', views.add_post, name='add_post'),
    path('add/tags/<int:post_id>/', views.add_tags, name='add_post_tags'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

mysite/mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static


sitemaps = {'posts': PostSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/blog/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth.models import User 
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager): 
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    class Meta:
        db_table = 'post'
        ordering = ('-publish',)

    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'))
    title = models.CharField(max_length=250) 
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', default='1')
    body = models.TextField() 
    publish = models.DateTimeField(default=timezone.now) 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='published')
    
    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.
    tags = TaggableManager()  # Tag manager

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=([
        self.publish.year, self.publish.month,
        self.publish.day, self.slug]))


class Comment(models.Model):
    class Meta:
        ordering = ('created',)

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms
from .models import Comment, Post


# email sharing form
class EmailPostForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'contact-from-text', 'placeholder': 'Your email address'}))
    to = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'contact-from-text', 'placeholder': 'Email address of recipient'}))
    comment = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'contact-from-text', 'placeholder': 'Your message'}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'contact-from-text', 'placeholder': 'Your name'}),
            'email': forms.EmailInput(attrs={'class': 'contact-from-text', 'placeholder': 'Your email address'}),
            'body': forms.Textarea(attrs={'class': 'contact-from-text', 'placeholder': 'Your message'}),
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'slug', 'body')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'contact-from-text', 'placeholder': 'Title of your post'}),
            'slug': forms.TextInput(attrs={'class': 'contact-from-text', 'placeholder': 'Post slug'}),
            'body': forms.Textarea(attrs={'class': 'contact-from-text', 'placeholder': 'Body of your post'}),
        }


class TagForm(forms.Form):
    tag = forms.CharField(widget=forms.TextInput(attrs={'class': 'contact-from-text', 'placeholder': 'Your tags'}))


class SearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={'class': 'contact-from-text', 'placeholder': 'Search for it'}))

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, PostForm, TagForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 4)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


# page of detail of post
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year,
                             publish__month=month, publish__day=day)

    # list of active comments for current post
    comments = post.comments.filter(active=True)

    new_comment = None

    # user sent comment
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    # if user enter data to forms
    # user sent comment
    if request.method == 'POST':
        form = EmailPostForm(request.POST)  # create form of data of user
        if form.is_valid():
            cd = form.cleaned_data  # read data of input
            post_url = request.build_absolute_uri(post.get_absolute_url())

            subject = post.title
            message = f'Link "{post_url}"\n{cd["comment"]}'
            send_mail(subject, message, 'kshatan03@gmail.com', [cd['to']])  # send mail
            sent = True  # true, when mail sent
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def add_post(request):
    add = False
    new_post = None

    if request.method == 'POST':
        add_form = PostForm(data=request.POST)
        if add_form.is_valid():
            new_post = add_form.save(commit=False)
            new_post.save()

            add = True

    else:
        add_form = PostForm()
    return render(request, 'blog/post/add.html', {
        'add': add,
        'add_form': add_form,
        'post': new_post
    })


def add_tags(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    add = False

    if request.method == 'POST':
        tag = TagForm(request.POST)
        if tag.is_valid():
            cd = tag.cleaned_data
            post.tags.add(cd['tag'])
            add = True
    else:
        tag = TagForm()
    return render(request, 'blog/post/add_tags.html', {
        'add': add,
        'tag': tag,
        'post': post
    })


def post_search(request):
    form = SearchForm()
    query = None
    results = list()
    if 'query' in request.GET:
        form = SearchForm(request.GET)
    if form.is_valid():
        query = form.cleaned_data['query']
        search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
        search_query = SearchQuery(query)
        results = Post.objects.annotate(search=search_vector, rank=SearchRank(search_vector, search_query)).filter(
            rank__gte=0.3).order_by('-rank')
    return render(request, 'blog/post/search.html', {'form': form,
                                                     'query': query,
                                                     'results': results})

mysite/blog/templates/blog/base - Copy.html
{% load static %}
{% load blog_tags %}

<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>

  <div id="sidebar">
    <p><a href="{% url "blog:post_feed" %}">RSS feed</a>and
      <a href="{% url "django.contrib.sitemaps.views.sitemap" %}">XML map</a></p>
    <p>Total created {% total_posts %} posts. <a href="{% url "blog:add_post" %}"> Add a new post</a></p>

    <h3>Latest posts</h3>
    {% show_latest_posts 3 %}

    <h3>Most commented posts</h3>
    {% get_most_commented_post as most %}

    <ul>
      {% for post in most %}
        {% with post.title as title %}
        <li><a href="{{ post.get_absolute_url }}">{{ title|truncatewords:5 }}</a></li>
        {% endwith %}
      {% endfor %}
    </ul>
  </div>
</body>
</html>

mysite/blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/blog.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

  <title>{% block title %}{% endblock %}</title>
</head>
<body>

  <aside class="my_left">
    <a href="{% url 'blog:post_list' %}"><img src="{% static 'img/logo.png' %}" alt="Logo"></a>
    <span class="logo">pyBlog</span>
    <ul>
      <a href="{% url 'blog:post_list' %}"><li><i class="fas fa-home"></i> Blog</li></a>
      <a href="{% url 'blog:add_post' %}"><li><i class="fas fa-plus"></i> New</li></a>
      <a href="{% url 'blog:post_feed' %}"><li><i class="fas fa-rss"></i> RSS</li></a>
      <a href="{% url 'django.contrib.sitemaps.views.sitemap' %}"><li><i class="fab fa-xing"></i> XML</li></a>
    </ul>
    <p class="total">Total created {% total_posts %} posts.</p>
  </aside>
  <main>
    <div class="features">
      <div class="cont">
        <div class="box">
            <a href="{% url 'blog:post_search' %}"><i class="fas fa-search"></i></a>
        </div>
      </div>

      {% block content %}
      {% endblock %}
    </div>
  </main>


    <div class="rightbar">

      <h3>Latest posts</h3>
      {% show_latest_posts 3 %}

      <h3>Most commented posts</h3>
      {% get_most_commented_post as most %}

      <ul>
        {% for post in most %}
          {% with post.title as title %}
          <li><a href="{{ post.get_absolute_url }}">{{ title|truncatewords:5 }}</a></li>
          {% endwith %}
        {% endfor %}
      </ul>

      <div class="sm">
        <a href="https://www.instagram.com/badlguy/"><i class="fab fa-instagram"></i></a>
        <a href="https://teleg.run/mgkskies"><i class="fab fa-telegram"></i></a>
        <a href="https://github.com/AlexiGarmash/"><i class="fab fa-github"></i></a>
      </div>
    </div>
</body>
</html>